version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/domain.conf:/etc/nginx/conf.d/domain.conf:ro
      # - ./config/certbot/www:/var/www/certbot/:ro
      - ./logs/nginx:/var/log/nginx
      - /home/ubuntu/nginx:/etc/ssl:ro
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./config/certbot/www:/var/www/certbot:rw